export type LandingLocationCategory = "static" | "bridge-panel";

export interface LandingLocation {
  id: string;
  slide: number;
  category: LandingLocationCategory;
  name: string;
  size: string;
  from: string;
  toward: string | null;
  availability: string;
  image: string;
}

export const landingLocationCategories: Array<{
  id: LandingLocationCategory;
  label: string;
  shortLabel: string;
}> = [
  { id: "static", label: "OOH Static Media", shortLabel: "Static Media" },
  { id: "bridge-panel", label: "OOH Media Static Bridge Panels", shortLabel: "Bridge Panels" },
];

export const landingLocations: LandingLocation[] = [
  {
    id: "03-dha-exit-cantt",
    slide: 3,
    category: "static",
    name: "DHA Exit Cantt",
    size: "60x40",
    from: "DHA Main Boulevard",
    toward: "Cavalry Ground, Cantt",
    availability: "30.June.26",
    image: "/landing-locations/location-03.jpg",
  },
  {
    id: "04-dha-phase-6-near-kfc",
    slide: 4,
    category: "static",
    name: "DHA Phase 6 Near KFC",
    size: "60x30",
    from: "DHA Phase 7",
    toward: "Dolmen Mall",
    availability: "30.June.26",
    image: "/landing-locations/location-04.jpg",
  },
  {
    id: "05-airport-road-dha-to-airport",
    slide: 5,
    category: "static",
    name: "Airport Road",
    size: "60x20",
    from: "DHA",
    toward: "Airport",
    availability: "15.July.26",
    image: "/landing-locations/location-05.jpg",
  },
  {
    id: "06-airport-road-airport-to-dha",
    slide: 6,
    category: "static",
    name: "Airport Road",
    size: "60x20",
    from: "Airport",
    toward: "DHA",
    availability: "30.June.26 (Ext)",
    image: "/landing-locations/location-06.jpg",
  },
  {
    id: "07-sher-pao-bridge",
    slide: 7,
    category: "static",
    name: "Sher Pao Bridge",
    size: "60x20",
    from: "Gulberg",
    toward: "Cantt",
    availability: "08.July.26",
    image: "/landing-locations/location-07.jpg",
  },
  {
    id: "08-ring-road-near-dha-dolmen-mall-airport",
    slide: 8,
    category: "static",
    name: "Ring Road Near DHA Dolmen Mall",
    size: "50x25",
    from: "Airport",
    toward: "Lake City",
    availability: "Current",
    image: "/landing-locations/location-08.jpg",
  },
  {
    id: "09-ring-road-near-dha-dolmen-mall-lake-city",
    slide: 9,
    category: "static",
    name: "Ring Road Near DHA Dolmen Mall",
    size: "50x25",
    from: "Lake City",
    toward: "Airport",
    availability: "30.June.26",
    image: "/landing-locations/location-09.jpg",
  },
  {
    id: "10-jinnah-flyover-cavalry-ground",
    slide: 10,
    category: "static",
    name: "Jinnah Flyover",
    size: "40x30",
    from: "Cavalry Ground",
    toward: "Firdous Market",
    availability: "01.July.26",
    image: "/landing-locations/location-10.jpg",
  },
  {
    id: "11-bop-roundabout-valencia",
    slide: 11,
    category: "static",
    name: "BOP Roundabout Valencia",
    size: "160x30",
    from: "Lake City & DHA Rahbar",
    toward: "Shaukat Khanum",
    availability: "20.July.26 (Strong Hold)",
    image: "/landing-locations/location-11.jpg",
  },
  {
    id: "12-bop-round-about-valencia",
    slide: 12,
    category: "static",
    name: "BOP Round About, Valencia",
    size: "60x40",
    from: "Chattri Chowk",
    toward: "DHA Rahbar, Lake City",
    availability: "Current (Strong Hold)",
    image: "/landing-locations/location-12.jpg",
  },
  {
    id: "13-jinnah-flyover-dha-cantt",
    slide: 13,
    category: "static",
    name: "Jinnah Flyover",
    size: "30x40",
    from: "DHA, Cantt.",
    toward: "Gulberg",
    availability: "26.June.26",
    image: "/landing-locations/location-13.jpg",
  },
  {
    id: "14-gulberg-main-market-roundabout",
    slide: 14,
    category: "static",
    name: "Gulberg Main Market Roundabout",
    size: "40x30",
    from: "Main Boulevard Main Market",
    toward: null,
    availability: "12.July.26 (Strong Hold)",
    image: "/landing-locations/location-14.jpg",
  },
  {
    id: "15-wapda-town",
    slide: 15,
    category: "static",
    name: "Wapda Town",
    size: "80x30",
    from: "Ever Care Hospital, Ameer Chowk",
    toward: "Shaukat Khanum Hospital",
    availability: "21.June.26",
    image: "/landing-locations/location-15.jpg",
  },
  {
    id: "16-g-1-johar-town-40x30",
    slide: 16,
    category: "static",
    name: "G-1 Johar Town",
    size: "40x30",
    from: "Emporium",
    toward: "Doctor Hospital",
    availability: "13.July.26",
    image: "/landing-locations/location-16.jpg",
  },
  {
    id: "17-g-1-johar-town-30x25",
    slide: 17,
    category: "static",
    name: "G-1 Johar Town",
    size: "30x25",
    from: "Emporium",
    toward: "Doctor Hospital",
    availability: "08.Aug.26",
    image: "/landing-locations/location-17.jpg",
  },
  {
    id: "18-bop-round-about-valencia-site-1",
    slide: 18,
    category: "static",
    name: "BOP Round About, Valencia, Johar Town - Site 1",
    size: "60x20",
    from: "Chattri Chowk & Rahbar DHA",
    toward: null,
    availability: "01.Aug.26",
    image: "/landing-locations/location-18.jpg",
  },
  {
    id: "19-bop-round-about-valencia-site-2",
    slide: 19,
    category: "static",
    name: "BOP Round About, Valencia, Johar Town - Site 2",
    size: "60x20",
    from: "Chattri Chowk & Rahbar DHA",
    toward: null,
    availability: "03.Aug.26",
    image: "/landing-locations/location-19.jpg",
  },
  {
    id: "20-pine-avenue-road-before-shell-pump",
    slide: 20,
    category: "static",
    name: "Pine Avenue Road Before Shell Pump",
    size: "60x20",
    from: "BOP Roundabout",
    toward: "Shanu Baba",
    availability: "05.Aug.26 (Ext)",
    image: "/landing-locations/location-20.jpg",
  },
  {
    id: "21-shahkaam-flyover-eme",
    slide: 21,
    category: "static",
    name: "Shahkaam Flyover",
    size: "40x30",
    from: "EME",
    toward: "Bahria Town",
    availability: "Current (Strong Hold)",
    image: "/landing-locations/location-21.jpg",
  },
  {
    id: "22-shahkaam-flyover-bahria-town",
    slide: 22,
    category: "static",
    name: "Shahkaam Flyover",
    size: "60x20",
    from: "Bahria Town",
    toward: "EME",
    availability: "Current",
    image: "/landing-locations/location-22.jpg",
  },
  {
    id: "24-race-course-chowk-gulberg",
    slide: 24,
    category: "bridge-panel",
    name: "Race Course Chowk, Jail Road, in Front of Jillani Park",
    size: "70x10",
    from: "Gulberg",
    toward: "Shadman Chowk",
    availability: "11.Sep.26",
    image: "/landing-locations/location-24.jpg",
  },
  {
    id: "25-race-course-chowk-shadman",
    slide: 25,
    category: "bridge-panel",
    name: "Race Course Chowk, Jail Road, in Front of Jillani Park",
    size: "70x10",
    from: "Shadman Chowk",
    toward: "Gulberg",
    availability: "17.July.26 (Ext)",
    image: "/landing-locations/location-25.jpg",
  },
  {
    id: "26-askari-9-cantt-saddar",
    slide: 26,
    category: "bridge-panel",
    name: "Askari 9 Cantt. Opp. Rangers",
    size: "132x07",
    from: "Saddar, Askari 9",
    toward: "Barki Road & Paragon",
    availability: "Current (Strong Hold)",
    image: "/landing-locations/location-26.jpg",
  },
  {
    id: "27-askari-9-cantt-barki-road",
    slide: 27,
    category: "bridge-panel",
    name: "Askari 9 Cantt. Opp. Rangers",
    size: "132x07",
    from: "Barki Road & Paragon",
    toward: "Saddar, Askari 9",
    availability: "Current (Strong Hold)",
    image: "/landing-locations/location-27.jpg",
  },
  {
    id: "28-allah-hoo-chowk-johar-town",
    slide: 28,
    category: "bridge-panel",
    name: "Allah Hoo Chowk, Johar Town",
    size: "115x15",
    from: "Shoq Chowk, Moulana Shaukat Ali Road",
    toward: "Shaukat Khanum Flyover",
    availability: "06.July.26",
    image: "/landing-locations/location-28.jpg",
  },
  {
    id: "29-khayaban-e-jinnah-near-pak-turk-school-shaukat-khanum",
    slide: 29,
    category: "bridge-panel",
    name: "Khayaban-e-Jinnah Road Near Pak Turk School, Johar Town",
    size: "50x10",
    from: "Shaukat Khanum Flyover",
    toward: "Chattri Chowk Valencia",
    availability: "31.July.26 (Ext)",
    image: "/landing-locations/location-29.jpg",
  },
  {
    id: "30-khayaban-e-jinnah-near-pak-turk-school-chattri-chowk",
    slide: 30,
    category: "bridge-panel",
    name: "Khayaban-e-Jinnah Road Near Pak Turk School, Johar Town",
    size: "50x10",
    from: "Chattri Chowk Valencia",
    toward: "Shaukat Khanum Flyover",
    availability: "14.July.26 (Ext)",
    image: "/landing-locations/location-30.jpg",
  },
  {
    id: "31-khayaban-e-jinnah-wapda-town-shaukat-khanum",
    slide: 31,
    category: "bridge-panel",
    name: "Khayaban-e-Jinnah Road in Front of Wapda Town Society Gate #02",
    size: "60x10",
    from: "Shaukat Khanum Flyover",
    toward: "Chattri Chowk Valencia",
    availability: "21.Aug.26",
    image: "/landing-locations/location-31.jpg",
  },
  {
    id: "32-khayaban-e-jinnah-wapda-town-chattri-chowk",
    slide: 32,
    category: "bridge-panel",
    name: "Khayaban-e-Jinnah Road in Front of Wapda Town Society Gate #02",
    size: "60x10",
    from: "Chattri Chowk Valencia",
    toward: "Shaukat Khanum Flyover",
    availability: "22.Aug.26",
    image: "/landing-locations/location-32.jpg",
  },
  {
    id: "33-wafaqi-colony-campus-underpass",
    slide: 33,
    category: "bridge-panel",
    name: "Wafaqi Colony Near Doctors Hospital",
    size: "55x10",
    from: "Campus Underpass",
    toward: "Thokar Niaz Baig",
    availability: "14.Aug.26",
    image: "/landing-locations/location-33.jpg",
  },
  {
    id: "34-wafaqi-colony-thokar-niaz-baig",
    slide: 34,
    category: "bridge-panel",
    name: "Wafaqi Colony Near Doctors Hospital",
    size: "55x10",
    from: "Thokar Niaz Baig",
    toward: "Campus Underpass",
    availability: "27.June.26",
    image: "/landing-locations/location-34.jpg",
  },
];
