export type MediaLocationCategory = "static" | "motorway" | "digital" | "bridge-panel" | "toll-plaza";

export interface MediaLocation {
  id: string;
  slide: number;
  city: string;
  section: string;
  category: MediaLocationCategory;
  name: string;
  size: string;
  from: string | null;
  toward: string | null;
  rent: string | null;
  availability: string | null;
  details: string | null;
  image: string;
}

export const mediaKitGeneratedFrom = "Crown Advertising Updated Media 08.May.26.pptx";

export const mediaKitCities = [
  "LAHORE",
  "SHEIKHUPURA",
  "FAISALABAD",
  "GUJRANWALA",
  "TOLL PLAZAS"
] as const;

export const mediaKitSections = [
  "OOH STATIC MEDIA",
  "OOH MEDIA M-2 & RING ROAD",
  "OOH DIGITAL MEDIA",
  "OOH MEDIA STATIC BRIDGE PANELS",
  "OOH MEDIA"
] as const;

export const mediaKitCategoryLabels: Record<MediaLocationCategory, string> = {
  "static": "Static OOH",
  "motorway": "M-2 & Ring Road",
  "digital": "Digital SMD",
  "bridge-panel": "Bridge Panels",
  "toll-plaza": "Toll Plazas"
};

export const mediaKitLocations: MediaLocation[] = [
  {
    "id": "03-dha-exit-cantt",
    "slide": 3,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "DHA Exit Cantt",
    "size": "60x40",
    "from": "DHA Main Boulevard",
    "toward": "Cavalry Ground, Cantt",
    "rent": "5 Million",
    "availability": "Current",
    "details": null,
    "image": "/media-kit/slide-03.jpeg"
  },
  {
    "id": "04-dha-phase-6-near-kfc",
    "slide": 4,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "DHA Phase 6 Near KFC",
    "size": "60x30",
    "from": "DHA Phase 7",
    "toward": "Dolmen Mall",
    "rent": "3.5 Million",
    "availability": "20.May.26",
    "details": null,
    "image": "/media-kit/slide-04.jpeg"
  },
  {
    "id": "05-airport-road",
    "slide": 5,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Airport Road",
    "size": "60x20",
    "from": "DHA",
    "toward": "Airport",
    "rent": "1,050,000",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-05.jpeg"
  },
  {
    "id": "06-airport-road",
    "slide": 6,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Airport Road",
    "size": "60x20",
    "from": "Airport",
    "toward": "DHA",
    "rent": "1,050,000",
    "availability": "08.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-06.jpeg"
  },
  {
    "id": "07-sher-pao-bridge",
    "slide": 7,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Sher Pao Bridge",
    "size": "60x20",
    "from": "Gulberg",
    "toward": "Cantt",
    "rent": "2,300,000",
    "availability": "Current (Hold)",
    "details": null,
    "image": "/media-kit/slide-07.jpeg"
  },
  {
    "id": "08-ring-road-near-dha-dolmen-mall",
    "slide": 8,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Ring Road Near DHA Dolmen Mall",
    "size": "50x25",
    "from": "Airport",
    "toward": "Lake City",
    "rent": "1,250,000",
    "availability": "08.May.26",
    "details": null,
    "image": "/media-kit/slide-08.jpeg"
  },
  {
    "id": "09-ring-road-near-dha-dolmen-mall",
    "slide": 9,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Ring Road Near DHA Dolmen Mall",
    "size": "50x25",
    "from": "Lake City",
    "toward": "Airport",
    "rent": "1,250,000",
    "availability": "20.May.26",
    "details": null,
    "image": "/media-kit/slide-09.jpeg"
  },
  {
    "id": "10-jinnah-flyover",
    "slide": 10,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Jinnah Flyover",
    "size": "40x30",
    "from": "Cavalry Ground",
    "toward": "Firdous Market",
    "rent": "1.8 Million",
    "availability": "01.June.26",
    "details": null,
    "image": "/media-kit/slide-10.jpeg"
  },
  {
    "id": "11-bop-roundabout-valencia",
    "slide": 11,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "BOP Roundabout Valencia",
    "size": "160x30",
    "from": "Lake City & DHA Rahbar",
    "toward": "Shaukat Khanum",
    "rent": "3.5 Million",
    "availability": "21.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-11.jpeg"
  },
  {
    "id": "12-bop-round-about-valencia",
    "slide": 12,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "BOP Round About, Valencia",
    "size": "60x40",
    "from": "Chattri Chowk",
    "toward": "DHA Rahbar, Lake City",
    "rent": "2 Million",
    "availability": "15.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-12.jpeg"
  },
  {
    "id": "13-jinnah-flyover",
    "slide": 13,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Jinnah Flyover",
    "size": "30x40",
    "from": "DHA, Cantt.",
    "toward": "Gulberg",
    "rent": "1.8 Million",
    "availability": "Current",
    "details": null,
    "image": "/media-kit/slide-13.jpeg"
  },
  {
    "id": "14-gulberg-main-market-roundabout",
    "slide": 14,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Gulberg Main Market Roundabout",
    "size": "40x30",
    "from": "Main Boulevard Main Market",
    "toward": null,
    "rent": "1.4 Million",
    "availability": "15.May.26",
    "details": null,
    "image": "/media-kit/slide-14.png"
  },
  {
    "id": "15-wapda-town",
    "slide": 15,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Wapda Town",
    "size": "80x30",
    "from": "Ever Care Hospital, Ameer Chowk",
    "toward": "Shaukat Khanum Hospital",
    "rent": "2.5 Million",
    "availability": "08.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-15.jpg"
  },
  {
    "id": "16-g-1-johar-town",
    "slide": 16,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "G-1 Johar Town",
    "size": "40x30",
    "from": "Emporium",
    "toward": "Doctor Hospital",
    "rent": "1,050,000",
    "availability": "10.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-16.jpeg"
  },
  {
    "id": "17-g-1-johar-town",
    "slide": 17,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "G-1 Johar Town",
    "size": "30x25",
    "from": "Emporium",
    "toward": "Doctor Hospital",
    "rent": "750,000",
    "availability": "09.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-17.jpeg"
  },
  {
    "id": "18-icchra-ferozpur-road",
    "slide": 18,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Icchra Ferozpur Road",
    "size": "40x30",
    "from": "Muslim Town Flyover",
    "toward": "Qartaba Chowk",
    "rent": "750,000",
    "availability": "09.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-18.jpeg"
  },
  {
    "id": "19-chuburji-chowk",
    "slide": 19,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Chuburji Chowk",
    "size": "50x25",
    "from": "Samanabad & Qartaba Chowk",
    "toward": "Bhatti Chowk & Railway Station",
    "rent": "850,000",
    "availability": "09.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-19.jpeg"
  },
  {
    "id": "20-bop-round-about-valencia-johar-town",
    "slide": 20,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "BOP Round About, Valencia, Johar Town",
    "size": "60x20",
    "from": "Chattri Chowk & Rahbar DHA",
    "toward": null,
    "rent": "1.2 Million",
    "availability": "10.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-20.png"
  },
  {
    "id": "21-bop-round-about-valencia-johar-town",
    "slide": 21,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "BOP Round About, Valencia, Johar Town",
    "size": "60x20",
    "from": "Chattri Chowk & Rahbar DHA",
    "toward": null,
    "rent": "1.2 Million",
    "availability": "16.May.26 (Hold)",
    "details": null,
    "image": "/media-kit/slide-21.jpeg"
  },
  {
    "id": "22-pine-avenue-road-before-shell-pump",
    "slide": 22,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Pine Avenue Road Before Shell Pump",
    "size": "60x20",
    "from": "BOP Roundabout",
    "toward": "Shano Baba",
    "rent": "1.2 Million",
    "availability": "01.June.26",
    "details": null,
    "image": "/media-kit/slide-22.jpeg"
  },
  {
    "id": "23-thokar-chowk",
    "slide": 23,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Thokar Chowk",
    "size": "30x30",
    "from": "Canal",
    "toward": "Multan Road, Raiwind Road",
    "rent": "850,000",
    "availability": "10.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-23.jpg"
  },
  {
    "id": "24-shahkaam-flyover",
    "slide": 24,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Shahkaam Flyover",
    "size": "40x30",
    "from": "EME",
    "toward": "Bahria Town",
    "rent": "1,050,000",
    "availability": "08.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-24.png"
  },
  {
    "id": "25-shahkaam-flyover",
    "slide": 25,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Shahkaam Flyover",
    "size": "60x20",
    "from": "Bahria Town",
    "toward": "EME",
    "rent": "1,050,000",
    "availability": "10.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-25.png"
  },
  {
    "id": "26-model-town-link-road-signal",
    "slide": 26,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Model Town Link Road Signal",
    "size": "50x25",
    "from": "Model Town Link Road",
    "toward": "Township",
    "rent": "1,050,000",
    "availability": "10.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-26.jpeg"
  },
  {
    "id": "27-g-1-market-chowk-johar-town",
    "slide": 27,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "G-1 Market Chowk Johar Town",
    "size": "60x20",
    "from": "Canal Road & Dr. Hospital",
    "toward": "Emporium Mall, Expo Centre",
    "rent": "1,050,000",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-27.jpeg"
  },
  {
    "id": "28-yadgar-flyover",
    "slide": 28,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Yadgar Flyover",
    "size": "40x30",
    "from": "Bhatti",
    "toward": "Yadgar",
    "rent": "800,000",
    "availability": "25.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-28.jpg"
  },
  {
    "id": "29-station-chowk",
    "slide": 29,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Station Chowk",
    "size": "30x50",
    "from": "Lari Adda",
    "toward": "Garhi Shahu & Empress Road",
    "rent": "1 Million",
    "availability": "26.May.26(Ext)",
    "details": null,
    "image": "/media-kit/slide-29.png"
  },
  {
    "id": "30-band-road-near-gulshan-e-ravi",
    "slide": 30,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Band Road Near Gulshan-e-Ravi",
    "size": "60x20",
    "from": "Babu Sabu Motorway",
    "toward": "Gulshan-e-Ravi & Ring Road",
    "rent": "550,000",
    "availability": "15.May.26 (Strong Hold)",
    "details": null,
    "image": "/media-kit/slide-30.jpeg"
  },
  {
    "id": "31-shahdara-chowk-flyover",
    "slide": 31,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Shahdara Chowk Flyover",
    "size": "60x20",
    "from": "Ravi Toll Plaza",
    "toward": "Sheikhupura & Gujranwala",
    "rent": "650,000",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-31.jpeg"
  },
  {
    "id": "32-ring-road-opp-eastern-housing",
    "slide": 32,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Ring Road Opp. Eastern Housing",
    "size": "90x30",
    "from": "Sialkot Motorway",
    "toward": "DHA, Airport",
    "rent": "1.5 Million",
    "availability": "08.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-32.jpeg"
  },
  {
    "id": "33-eastern-bypass-toll-plaza-lahore-entrance",
    "slide": 33,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Eastern Bypass Toll Plaza, Lahore Entrance",
    "size": "90x30",
    "from": "Islamabad & Sialkot Motorway",
    "toward": "Lahore",
    "rent": "850,000",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-33.jpeg"
  },
  {
    "id": "34-eastern-bypass-near-toll-plaza",
    "slide": 34,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Eastern Bypass Near Toll Plaza",
    "size": "90x30",
    "from": "Islamabad & Sialkot Motorway",
    "toward": "Lahore",
    "rent": "850,000",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-34.jpeg"
  },
  {
    "id": "35-eastern-bypass-sialkot-motorway",
    "slide": 35,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Eastern Bypass Sialkot Motorway",
    "size": "90x30",
    "from": "Lahore",
    "toward": "Sialkot & Kala Shah Kaku",
    "rent": "850,000",
    "availability": "09.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-35.jpeg"
  },
  {
    "id": "36-dosako-chowk-kot-abdul-malik",
    "slide": 36,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Dosako Chowk Kot Abdul Malik",
    "size": "45x15",
    "from": "Al-Saeed Chowk Saggian Bridge",
    "toward": "Sheikhupura, Shahdara",
    "rent": "150,000",
    "availability": "23.May.26",
    "details": null,
    "image": "/media-kit/slide-36.jpeg"
  },
  {
    "id": "37-toll-plaza-kot-abdul-malik",
    "slide": 37,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Toll Plaza Kot Abdul Malik",
    "size": "60x20",
    "from": "Lahore",
    "toward": "Sheikhupura",
    "rent": null,
    "availability": "08.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-37.jpeg"
  },
  {
    "id": "38-opp-al-rehman-garden-sharqpur-road",
    "slide": 38,
    "city": "LAHORE",
    "section": "OOH STATIC MEDIA",
    "category": "static",
    "name": "Opp. Al - Rehman Garden Sharqpur Road",
    "size": "60x20",
    "from": "Shahdara & Al Saeed Chowk",
    "toward": "M-2 Faizpur Interchange & Sharqpur",
    "rent": "250,000",
    "availability": "02.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-38.jpeg"
  },
  {
    "id": "40-m-2-motorway-near-ravi-toll-plaza",
    "slide": 40,
    "city": "LAHORE",
    "section": "OOH MEDIA M-2 & RING ROAD",
    "category": "motorway",
    "name": "M-2 Motorway Near Ravi Toll Plaza",
    "size": "90x30",
    "from": "Lahore",
    "toward": "Islamabad & Karachi Motorway",
    "rent": "750,000",
    "availability": "Current",
    "details": null,
    "image": "/media-kit/slide-40.jpg"
  },
  {
    "id": "41-motorway-near-ravi-toll-plaza",
    "slide": 41,
    "city": "LAHORE",
    "section": "OOH MEDIA M-2 & RING ROAD",
    "category": "motorway",
    "name": "Motorway Near Ravi Toll Plaza",
    "size": "90x30",
    "from": "Islamabad",
    "toward": "Lahore",
    "rent": "750,000",
    "availability": "09.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-41.jpeg"
  },
  {
    "id": "42-lahore-bypass-motorway",
    "slide": 42,
    "city": "LAHORE",
    "section": "OOH MEDIA M-2 & RING ROAD",
    "category": "motorway",
    "name": "Lahore Bypass Motorway",
    "size": "60x20",
    "from": "Lahore & Islamabad",
    "toward": "Kala Shah Kaku Interchange",
    "rent": "350,000",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-42.jpeg"
  },
  {
    "id": "44-model-town-link-road-smd",
    "slide": 44,
    "city": "LAHORE",
    "section": "OOH DIGITAL MEDIA",
    "category": "digital",
    "name": "Model Town Link Road SMD",
    "size": "40x20",
    "from": "Model Town Link Road",
    "toward": "Akbar Chowk Flyover",
    "rent": "Rate per slot: 500,000",
    "availability": null,
    "details": "Rate per slot: 500,000",
    "image": "/media-kit/slide-44.png"
  },
  {
    "id": "45-g-1-market-smd",
    "slide": 45,
    "city": "LAHORE",
    "section": "OOH DIGITAL MEDIA",
    "category": "digital",
    "name": "G-1 Market SMD",
    "size": "20x10",
    "from": "Emporium Mall",
    "toward": "Canal Road",
    "rent": "Rate per slot: 400,000",
    "availability": null,
    "details": "Rate per slot: 400,000",
    "image": "/media-kit/slide-45.png"
  },
  {
    "id": "46-main-boulevard-gulberg-in-front-of-hafeez-centre-smd",
    "slide": 46,
    "city": "LAHORE",
    "section": "OOH DIGITAL MEDIA",
    "category": "digital",
    "name": "Main Boulevard Gulberg In Front of Hafeez Centre SMD",
    "size": "40x10",
    "from": "Liberty Chowk",
    "toward": "Main Market, Jail Road",
    "rent": "Rate per slot: 600,000",
    "availability": null,
    "details": "Rate per slot: 600,000",
    "image": "/media-kit/slide-46.png"
  },
  {
    "id": "47-main-boulevard-gulberg-in-front-of-hafeez-centre-smd",
    "slide": 47,
    "city": "LAHORE",
    "section": "OOH DIGITAL MEDIA",
    "category": "digital",
    "name": "Main Boulevard Gulberg In Front of Hafeez Centre SMD",
    "size": "40x10",
    "from": "Main Market, Jail Road",
    "toward": "Liberty Chowk",
    "rent": "Rate per slot: 600,000",
    "availability": null,
    "details": "Rate per slot: 600,000",
    "image": "/media-kit/slide-47.jpeg"
  },
  {
    "id": "48-allah-hoo-chowk-johar-town-smd",
    "slide": 48,
    "city": "LAHORE",
    "section": "OOH DIGITAL MEDIA",
    "category": "digital",
    "name": "Allah Hoo Chowk Johar Town SMD",
    "size": "40x10",
    "from": "Shaukat Khanum Flyover",
    "toward": "Shoq Chowk, Moulana Shaukat Ali Road",
    "rent": "Rate per slot: 600,000",
    "availability": null,
    "details": "Rate per slot: 600,000",
    "image": "/media-kit/slide-48.png"
  },
  {
    "id": "49-qaddafi-stadium-ferozepur-road-smd",
    "slide": 49,
    "city": "LAHORE",
    "section": "OOH DIGITAL MEDIA",
    "category": "digital",
    "name": "Qaddafi Stadium Ferozepur Road SMD",
    "size": "48x12",
    "from": "Muslim Town",
    "toward": "Kalma Chowk",
    "rent": "Rate per slot: 600,000",
    "availability": null,
    "details": "Rate per slot: 600,000",
    "image": "/media-kit/slide-49.jpeg"
  },
  {
    "id": "51-race-course-chowk-jail-road-in-front-of-jillani-park",
    "slide": 51,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Race Course Chowk Jail Road In Front of Jillani Park",
    "size": "70x10",
    "from": "Gulberg",
    "toward": "Shadman Chowk",
    "rent": "2.5 Million",
    "availability": "10.July.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-51.jpg"
  },
  {
    "id": "52-race-course-chowk-jail-road-in-front-of-jillani-park",
    "slide": 52,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Race Course Chowk Jail Road In Front of Jillani Park",
    "size": "70x10",
    "from": "Shadman Chowk",
    "toward": "Gulberg",
    "rent": "2.5 Million",
    "availability": "15.June.26",
    "details": null,
    "image": "/media-kit/slide-52.jpeg"
  },
  {
    "id": "53-askari-9-cantt-opp-rangers",
    "slide": 53,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Askari 9 Cantt. Opp. Rangers",
    "size": "132x07",
    "from": "Saddar, Askari 9",
    "toward": "Barki Road & Paragon",
    "rent": "1.5 Million",
    "availability": "10.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-53.jpeg"
  },
  {
    "id": "54-askari-9-cantt-opp-rangers",
    "slide": 54,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Askari 9 Cantt. Opp. Rangers",
    "size": "132x07",
    "from": "Barki Road & Paragon",
    "toward": "Saddar, Askari 9",
    "rent": "1.5 Million",
    "availability": "Current (Strong Hold)",
    "details": null,
    "image": "/media-kit/slide-54.jpeg"
  },
  {
    "id": "55-allah-hoo-chowk-johar-town-site-01",
    "slide": 55,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Allah Hoo Chowk, Johar Town - Site 01",
    "size": "70x15",
    "from": "Shoq Chowk, Moulana Shaukat Ali Road",
    "toward": "Shaukat Khanum Flyover",
    "rent": "1.8 Million",
    "availability": "10.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-55.png"
  },
  {
    "id": "56-allah-hoo-chowk-johar-town-site-02",
    "slide": 56,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Allah Hoo Chowk, Johar Town - Site 02",
    "size": "45x15",
    "from": "Shoq Chowk, Moulana Shaukat Ali Road",
    "toward": "Shaukat Khanum Flyover",
    "rent": "900,000",
    "availability": "Current (Hold)",
    "details": null,
    "image": "/media-kit/slide-56.png"
  },
  {
    "id": "57-khayaban-e-jinnah-road-near-pak-turk-school-johar-town",
    "slide": 57,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Khayaban-e-Jinnah Road Near Pak Turk School Johar Town",
    "size": "50x10",
    "from": "Shaukat Khanum Flyover",
    "toward": "Chattri Chowk Valencia",
    "rent": "1.2 Million",
    "availability": "01.June.26",
    "details": null,
    "image": "/media-kit/slide-57.jpeg"
  },
  {
    "id": "58-khayaban-e-jinnah-road-near-pak-turk-school-johar-town",
    "slide": 58,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Khayaban-e-Jinnah Road Near Pak Turk School Johar Town",
    "size": "50x10",
    "from": "Chattri Chowk Valencia",
    "toward": "Shaukat Khanum Flyover",
    "rent": "1.2 Million",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-58.jpg"
  },
  {
    "id": "59-khayaban-e-jinnah-road-in-front-of-wapda-town-society-gate-02",
    "slide": 59,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Khayaban-e-Jinnah Road In Front of Wapda Town Society Gate # 02",
    "size": "60x10",
    "from": "Shaukat Khanum Flyover",
    "toward": "Chattri Chowk Valencia",
    "rent": "1.2 Million",
    "availability": "16.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-59.jpeg"
  },
  {
    "id": "60-khayaban-e-jinnah-road-in-front-of-wapda-town-society-gate-02",
    "slide": 60,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Khayaban-e-Jinnah Road In Front of Wapda Town Society Gate # 02",
    "size": "60x10",
    "from": "Chattri Chowk Valencia",
    "toward": "Shaukat Khanum Flyover",
    "rent": "1.2 Million",
    "availability": "16.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-60.png"
  },
  {
    "id": "61-wafaqi-colony-near-doctors-hospital",
    "slide": 61,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Wafaqi Colony Near Doctors Hospital",
    "size": "55x10",
    "from": "Campus Underpass",
    "toward": "Thokar Niaz Baig",
    "rent": "1.2 Million",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-61.jpg"
  },
  {
    "id": "62-wafaqi-colony-near-doctors-hospital",
    "slide": 62,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Wafaqi Colony Near Doctors Hospital",
    "size": "55x10",
    "from": "Thokar Niaz Baig",
    "toward": "Campus Underpass",
    "rent": "1.2 Million",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-62.jpeg"
  },
  {
    "id": "63-canal-road-near-amir-town",
    "slide": 63,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Canal Road Near Amir Town",
    "size": "45x15",
    "from": "Harbanspura",
    "toward": "Mughalpura",
    "rent": "1.5 Million",
    "availability": "16.May.26",
    "details": null,
    "image": "/media-kit/slide-63.jpg"
  },
  {
    "id": "64-canal-road-near-amir-town",
    "slide": 64,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Canal Road Near Amir Town",
    "size": "45x15",
    "from": "Mughalpura",
    "toward": "Harbanspura",
    "rent": "1.5 Million",
    "availability": "16.May.26",
    "details": null,
    "image": "/media-kit/slide-64.jpg"
  },
  {
    "id": "65-canal-road-harbanspura",
    "slide": 65,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Canal Road Harbanspura",
    "size": "45x15",
    "from": "Jallo",
    "toward": "Mughalpura",
    "rent": "1.5 Million",
    "availability": "08.May.26 (Hold)",
    "details": null,
    "image": "/media-kit/slide-65.jpg"
  },
  {
    "id": "66-canal-road-harbanspura",
    "slide": 66,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Canal Road Harbanspura",
    "size": "45x15",
    "from": "Mughalpura",
    "toward": "Jallo",
    "rent": "1.5 Million",
    "availability": "07.June.26",
    "details": null,
    "image": "/media-kit/slide-66.jpg"
  },
  {
    "id": "67-shahdara-flyover-near-metro-station",
    "slide": 67,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Shahdara Flyover Near Metro Station",
    "size": "50x15",
    "from": "Gujranwala",
    "toward": "Lahore",
    "rent": "850,000",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-67.jpg"
  },
  {
    "id": "68-shahdara-flyover-near-metro-station",
    "slide": 68,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Shahdara Flyover Near Metro Station",
    "size": "60x15",
    "from": "Lahore",
    "toward": "Gujranwala",
    "rent": "850,000",
    "availability": "31.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-68.jpg"
  },
  {
    "id": "69-model-town",
    "slide": 69,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Model Town",
    "size": "65x12",
    "from": "Kalma Chowk",
    "toward": "Arfa Kareem Tower",
    "rent": "1.5 Million",
    "availability": "01.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-69.jpeg"
  },
  {
    "id": "70-model-town",
    "slide": 70,
    "city": "LAHORE",
    "section": "OOH MEDIA STATIC BRIDGE PANELS",
    "category": "bridge-panel",
    "name": "Model Town",
    "size": "58x12",
    "from": "Arfa Kareem Tower",
    "toward": "Kalma Chowk",
    "rent": "1.5 Million",
    "availability": "13.May.26",
    "details": null,
    "image": "/media-kit/slide-70.jpg"
  },
  {
    "id": "72-sheikhupura-32-chowk-roundabout",
    "slide": 72,
    "city": "SHEIKHUPURA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Sheikhupura 32 Chowk Roundabout",
    "size": "60x20",
    "from": "FSD",
    "toward": "Motorway",
    "rent": "350,000",
    "availability": "14.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-72.jpeg"
  },
  {
    "id": "73-motorway-chowk-sheikhupura",
    "slide": 73,
    "city": "SHEIKHUPURA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Motorway Chowk Sheikhupura",
    "size": "60x20",
    "from": "Motorway",
    "toward": "32 Chowk",
    "rent": "350,000",
    "availability": "Current (Hold)",
    "details": null,
    "image": "/media-kit/slide-73.jpeg"
  },
  {
    "id": "74-batti-chowk-sheikhupura",
    "slide": 74,
    "city": "SHEIKHUPURA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Batti Chowk Sheikhupura",
    "size": "60x20",
    "from": "Lahore",
    "toward": "Faisalabad Motorway & Saddar Chowk",
    "rent": "350,000",
    "availability": "Current (Booked from 15.May.26)",
    "details": null,
    "image": "/media-kit/slide-74.jpeg"
  },
  {
    "id": "75-batti-chowk-sheikhupura",
    "slide": 75,
    "city": "SHEIKHUPURA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Batti Chowk Sheikhupura",
    "size": "60x20",
    "from": "Lahore",
    "toward": "Faisalabad Motorway & Saddar Chowk",
    "rent": "350,000",
    "availability": "19.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-75.jpg"
  },
  {
    "id": "76-sheikhupura-gujranwala-road",
    "slide": 76,
    "city": "SHEIKHUPURA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Sheikhupura Gujranwala Road",
    "size": "60x20",
    "from": "Motorway",
    "toward": "32 Chowk",
    "rent": "250,000",
    "availability": "14.May.26",
    "details": null,
    "image": "/media-kit/slide-76.png"
  },
  {
    "id": "78-canal-road-rafhan-pulley",
    "slide": 78,
    "city": "FAISALABAD",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Canal Road Rafhan Pulley",
    "size": "60x20",
    "from": "Abdullahpur Underpass & Abdullahpur Chowk",
    "toward": "Lahore",
    "rent": "550,000",
    "availability": "On Call",
    "details": null,
    "image": "/media-kit/slide-78.jpeg"
  },
  {
    "id": "79-abdullah-under-pass-canal-road",
    "slide": 79,
    "city": "FAISALABAD",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Abdullah Under Pass Canal Road",
    "size": "60x20",
    "from": "Abdullah Under Pass",
    "toward": "Jhal Chowk, Satyana Road & Samundri Road",
    "rent": "550,000",
    "availability": "On Call",
    "details": null,
    "image": "/media-kit/slide-79.jpeg"
  },
  {
    "id": "80-mcdonald-s-chowk",
    "slide": 80,
    "city": "FAISALABAD",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "McDonald's Chowk",
    "size": "60x20",
    "from": "D Ground",
    "toward": "Satyana Road FSD",
    "rent": "550,000",
    "availability": "10.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-80.jpeg"
  },
  {
    "id": "81-satyana-road",
    "slide": 81,
    "city": "FAISALABAD",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Satyana Road",
    "size": "60x20",
    "from": "Saleemi Chowk",
    "toward": "D Ground FSD",
    "rent": "550,000",
    "availability": "10.June.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-81.jpeg"
  },
  {
    "id": "82-abdullahpur-bridge",
    "slide": 82,
    "city": "FAISALABAD",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Abdullahpur Bridge",
    "size": "40x20",
    "from": "Abdullahpur Bridge, Railway Station GTS FSD",
    "toward": null,
    "rent": null,
    "availability": "Long Term Booked",
    "details": null,
    "image": "/media-kit/slide-82.jpeg"
  },
  {
    "id": "84-flyover-gujranwala",
    "slide": 84,
    "city": "GUJRANWALA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Flyover Gujranwala",
    "size": "60x20",
    "from": "Model Town",
    "toward": "Satellite Town & Lahore",
    "rent": "400,000",
    "availability": "30.June.26",
    "details": null,
    "image": "/media-kit/slide-84.jpeg"
  },
  {
    "id": "85-chan-da-qilla-chowk",
    "slide": 85,
    "city": "GUJRANWALA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Chan Da Qilla Chowk",
    "size": "60x20",
    "from": "Lahore",
    "toward": "Gujranwala City & King Mall Wapda Town",
    "rent": "400,000",
    "availability": "30.May.26 (Ext)",
    "details": null,
    "image": "/media-kit/slide-85.jpeg"
  },
  {
    "id": "86-chan-da-qilla-chowk",
    "slide": 86,
    "city": "GUJRANWALA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Chan Da Qilla Chowk",
    "size": "60x20",
    "from": "Gujranwala",
    "toward": "Lahore",
    "rent": "350,000",
    "availability": "Current",
    "details": null,
    "image": "/media-kit/slide-86.jpeg"
  },
  {
    "id": "87-opp-gift-university",
    "slide": 87,
    "city": "GUJRANWALA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Opp. Gift University",
    "size": "60x20",
    "from": "Sialkot Bypass",
    "toward": "Pindi Bypass",
    "rent": "300,000",
    "availability": "17.May.26",
    "details": null,
    "image": "/media-kit/slide-87.jpeg"
  },
  {
    "id": "88-opp-gift-university",
    "slide": 88,
    "city": "GUJRANWALA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Opp. Gift University",
    "size": "60x20",
    "from": "Pindi Bypass",
    "toward": "Sialkot Bypass",
    "rent": "300,000",
    "availability": "05.June.26",
    "details": null,
    "image": "/media-kit/slide-88.jpeg"
  },
  {
    "id": "89-wapda-town",
    "slide": 89,
    "city": "GUJRANWALA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Wapda Town",
    "size": "60x20",
    "from": "Pindi Bypass",
    "toward": "Chan Da Qilla",
    "rent": "280,000",
    "availability": "25.May.26",
    "details": null,
    "image": "/media-kit/slide-89.jpeg"
  },
  {
    "id": "90-khan-plaza-gujranwala",
    "slide": 90,
    "city": "GUJRANWALA",
    "section": "OOH MEDIA",
    "category": "static",
    "name": "Khan Plaza Gujranwala",
    "size": "60x20",
    "from": "Chand Da Qila Chowk",
    "toward": "Kings Mall & Wapda town",
    "rent": "300,000",
    "availability": "Long Term Booked",
    "details": null,
    "image": "/media-kit/slide-90.jpeg"
  },
  {
    "id": "92-kot-abdulmalik-toll-plaza",
    "slide": 92,
    "city": "TOLL PLAZAS",
    "section": "OOH MEDIA",
    "category": "toll-plaza",
    "name": "Kot Abdulmalik Toll Plaza",
    "size": "211x08 (Double Side)",
    "from": "Lahore",
    "toward": "Sheikhupura",
    "rent": "850,000",
    "availability": "Booked",
    "details": null,
    "image": "/media-kit/slide-92.jpeg"
  },
  {
    "id": "93-sheikhupura-bypass-toll-plaza",
    "slide": 93,
    "city": "TOLL PLAZAS",
    "section": "OOH MEDIA",
    "category": "toll-plaza",
    "name": "Sheikhupura bypass Toll plaza",
    "size": "117x08 (Double Side)",
    "from": "Lahore Sheikhupura",
    "toward": "Faisalabad Sheikhupura",
    "rent": "850,000",
    "availability": "Current",
    "details": null,
    "image": "/media-kit/slide-93.jpeg"
  },
  {
    "id": "94-feroz-watwan-toll-plaza",
    "slide": 94,
    "city": "TOLL PLAZAS",
    "section": "OOH MEDIA",
    "category": "toll-plaza",
    "name": "Feroz Watwan Toll plaza",
    "size": "117x06 (Double Side)",
    "from": null,
    "toward": null,
    "rent": "850,000",
    "availability": "Current",
    "details": null,
    "image": "/media-kit/slide-94.png"
  },
  {
    "id": "95-shahkot-toll-plaza",
    "slide": 95,
    "city": "TOLL PLAZAS",
    "section": "OOH MEDIA",
    "category": "toll-plaza",
    "name": "Shahkot Toll Plaza",
    "size": "117x08 (Double Side)",
    "from": null,
    "toward": null,
    "rent": "850,000",
    "availability": "Current",
    "details": null,
    "image": "/media-kit/slide-95.jpeg"
  },
  {
    "id": "96-faisalabad-toll-plaza-gatwala",
    "slide": 96,
    "city": "TOLL PLAZAS",
    "section": "OOH MEDIA",
    "category": "toll-plaza",
    "name": "FAISALABAD Toll Plaza Gatwala",
    "size": "90x08 (Double Side)",
    "from": null,
    "toward": null,
    "rent": "850,000",
    "availability": "Current",
    "details": null,
    "image": "/media-kit/slide-96.jpeg"
  }
];
